### ISSUE TITLE
mysql.createPool support 

### ISSUE THREAD

**Issue by rraallvv** [lukechilds/keyv-mysql#35]
Any chances of using `mysql.createPool` for the DB connection?

**Comment by rraallvv** [comment]
I'm getting this error:

    Message: This socket has been ended by the other party
    Stacktrace:
    ====================
    Error: This socket has been ended by the other party
       at PromiseConnection.execute (node_modules/mysql2/promise.js:102:20)
       at sql (node_modules/@keyv/mysql/src/index.js:19:30)
       at connected.then.query (node_modules/@keyv/sql/src/index.js:39:19)

It might be related to keyv-mysql no using a pool, but I'm not entirely sure.

Keep up the good work.

**Comment by rraallvv** [comment]
Since the default values for a pool are ok for the average application (I guess), I'm using a pool instead like so:

                ...
                opts.connect = () => Promise.resolve()
                        .then(() => mysql.createPool(opts.uri))
                        .then(connection => {
                                return sql => connection.execute(sql)
                                        .then(data => data[0]);
                        });
                ...
