### ISSUE TITLE
Can't add new command when connection is in closed state

### ISSUE THREAD

**Issue by rraallvv** [lukechilds/keyv-mysql#38]
Stacktrace:
```
Error: Can't add new command when connection is in closed state
   at PromiseConnection.execute (node_modules/mysql2/promise.js:102:20)
   at sql (node_modules/@keyv/mysql/src/index.js:19:30)
   at connected.then.query (node_modules/@keyv/sql/src/index.js:39:19)
   at <anonymous>
   at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Comment by MysticCraftYT** [comment]
I have the same issue

**Comment by capwizz** [comment]
Has anyone found a fix for this?
